import SweetScroll from 'sweet-scroll';
export const refs = {
  headerIndex: document.querySelector('.header-index'),
  headerLibrary: document.querySelector('.header__library'),
  homeBtn: document.querySelector('.menu__home'),
  homeFirstBtn: document.querySelector('.current-home'),
  libraryBtn: document.querySelector('.menu__library'),
  librarySecondBtn: document.querySelector('.library-current'),
  searchForm: document.querySelector('#search-form'),
  footer: document.querySelector('footer'),
  langs: document.querySelector('.change-lng'),
  input: document.querySelector('.search__input'),
  search: document.querySelector('.chose-type'),
  
  errorSearch: document.querySelector('.warning-notification'),
  chosenNameBtn: document.querySelector('.search-choice-btn.name'),
  chosenGenreBtn: document.querySelector('.search-choice-btn.genre'),
  header: document.querySelector('.header-index'),
  homeGallery: document.querySelector('.home'),
  libraryGallery: document.querySelector('.watched'),
  headerEl: document.querySelector('header'),
  noMoviesAlert: document.querySelector('.alert-block'),
  galleryListEl: document.querySelector('#gallery-list'),
  galleryListWatchedEl: document.querySelector('.gallery__list-watched'),
  pageNavDivEl: document.querySelector('.pagination'),
  prevBtnEl: document.querySelector('.pagination_previousBtn'),
  nextBtnEl: document.querySelector('.pagination_nextBtn'),
  currentPageEl: document.querySelector('.pagination_currentPage'),
  firstPageEl: document.querySelector('.pagination_firstPage'),
  lastPageEl: document.querySelector('.pagination_lastPage'),
  leftPointsEl: document.querySelector('.pagination_leftPoints'),
  rightPointsEl: document.querySelector('.pagination_rightPoints'),
  rightFirstPageEl: document.querySelector('.pagination_rightFirstPage'),
  rightSecondPageEl: document.querySelector('.pagination_rightSecondPage'),
  leftFirstPageEl: document.querySelector('.pagination_leftFirstPage'),
  leftSecondPageEl: document.querySelector('.pagination_leftSecondPage'),
  genre: '',
  watchedListBtn: document.getElementById('js-WatchedButton'),
  queueListBtn: document.getElementById('js-QueueButton'),
  watchedListBtnInput: document.querySelector('[value="Watched"]'),
  queueListBtnInput: document.querySelector('[value="Queue"]'),
  currentPage: 1,
  totalPages: 1,
  scroller: new SweetScroll({ duration: 1000 }),
  pagSerchQuery: '',
 
  goTopBtn: document.querySelector('.button_to_top'),
 
  movieList: document.querySelector('main'),
  movieDetail: document.getElementById('modal-movie-detail'),
  movieTrailer: document.getElementById('modal-movie-trailer'),
  modalRegTitle: document.querySelector('.reg-modal-title'),
  
  modalRegAlready: document.querySelector('.already'),
  

  modalLogTitle: document.querySelector('.singIn-modal-title'),
  
  modalLogAlready: document.querySelector('.not-already'),
};
