const refs = {
  body: document.querySelector('body'),
  formSingUp: document.getElementById('reg-modal-form'),
  formSingIn: document.getElementById('singIn-modal-form'),
  logOutBtn: document.querySelector('.logout-btn'),
  singUpBtn: document.querySelector('[data-modal-open="singUp"]'),
  singInBtn: document.querySelector('[data-modal-open="singIn"]'),
  modalSingUpBtn: document.querySelector('[data-modal-open="singUp-second"]'),
  modalSingInBtn: document.querySelector('[data-modal-open="singIn-second"]'),
  formSingUpInputEmail: document.querySelector('.reg-modal-email'),
  formSingUpInputPassword: document.querySelector('.reg-modal-password'),
  formSingInInputEmail: document.querySelector('.singIn-modal-email'),
  formSingInInputPassword: document.querySelector('.singIn-modal-password'),
  backdropSingUp: document.querySelector('.backdrop-reg-modal'),
  btnCloseSingUp: document.querySelector('[data-modal-close="reg"]'),
  backdropSingIn: document.querySelector('.backdrop-singIn-modal'),
  btnCloseSingIn: document.querySelector('[data-modal-close="singIn"]'),
};

export const {
  body,
  formSingUp,
  formSingIn,
  logOutBtn,
  singUpBtn,
  singInBtn,
  modalSingUpBtn,
  modalSingInBtn,
  formSingUpInputEmail,
  formSingUpInputPassword,
  formSingInInputEmail,
  formSingInInputPassword,
  backdropSingUp,
  btnCloseSingUp,
  backdropSingIn,
  btnCloseSingIn,
} = refs;
