import './sass/index.scss';
import './js/headerToggle';
import './js/render';
import './js/modalMovie';
import './js/modalTeam';
import './js/changeTheme';
import './js/search';
import './js/goTopBtn';
import './js/auth/auth';
